version: '3.8'

services:
  backend:
    container_name: backend-tests
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    env_file:
      - backend/.env.test
