services:
  backend:
    container_name: backend
    image: backend:prod
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - 8000:8000
    env_file:
      - backend/.env.prod

  frontend:
    container_name: frontend
    image: frontend:prod
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production

  redis:
    container_name: redis
    image: redis:7
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  worker:
    container_name: worker
    image: backend:prod
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    restart: always
    depends_on:
      - redis
    command: python manage.py run_worker
    volumes:
      - ./backend:/app
    env_file:
      - backend/.env.prod

volumes:
  redis_data: