services:
  backend:
    container_name: backend
    image: backend:dev
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    depends_on:
      - db
      - redis
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    env_file:
      - backend/.env.dev

  db:
    container_name: db
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: veredict
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  frontend:
    container_name: frontend
    image: frontend:dev
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev

  redis:
    container_name: redis
    image: redis:7
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  worker:
    container_name: worker
    image: backend:dev
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    depends_on:
      - redis
      - db
    command: python manage.py run_worker
    volumes:
      - ./backend:/app
    env_file:
      - backend/.env.dev

volumes:
  postgres_data:
  redis_data: