services:
  backend:
    image: backend:prod
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - 8000:8000
    env_file:
      - backend/.env.prod

  frontend:
    image: frontend:prod
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production