services:
  backend:
    container_name: backend
    image: backend:dev
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    env_file:
      - backend/.env.dev

  db:
    container_name: db
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: lavocat
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  frontend:
    container_name: frontend
    image: frontend:dev
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev


volumes:
  postgres_data: