# Pull official base image
FROM python:3.10.0-alpine

# Set work directory
WORKDIR /app

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Install dependencies
RUN apk add --no-cache postgresql-dev build-base \
 && apk update \
 && apk add bash

COPY . .

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Expose port
EXPOSE 8000

# Start Gunicorn
CMD ["gunicorn", "veredict.wsgi:application", "--bind", "0.0.0.0:8000"]