# Generated by Django 3.1.7 on 2021-03-15 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='document_id',
            field=models.IntegerField(),
        ),
    ]
