# Generated by Django 3.1.7 on 2021-03-24 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0004_auto_20210315_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Documentação Pendente'), (2, 'Documentação Parcial'), (3, 'À Contatar')], default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendancefile',
            name='attendance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='files', to='attendances.attendance'),
        ),
    ]
