# Generated by Django 3.1.7 on 2021-03-27 23:00

from django.db import migrations, models
import veredict.attendances.models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0007_attendance_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancefile',
            name='file',
            field=models.FileField(upload_to=veredict.attendances.models.upload_to),
        ),
    ]
