# Generated by Django 3.1.7 on 2023-09-04 18:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('attendances', '0018_auto_20230904_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='services_provided',
            new_name='services_types',
        ),
    ]
