CITY_CODE_MAPPING = {
    "01": [
        "SAO BERNARDO DO CAMPO",
        "SAO PAULO",
        "GUARULHOS",
        "DIADEMA",
        "SAO CAETANO DO SUL",
        "MOGI DAS CRUZES",
        "SANTO ANDRE",
        "FRANCO DA ROCHA",
        "FRANCISCO MORATO",
        "MAIRIPORA",
        "CARAPICUIBA",
        "OSASCO",
        "SUZANO",
        "EMBU DAS ARTES",
        "SANTA ISABEL",
        "SANTANA DE PERNAÍBA",
        "PIRAPORA DO BOM JESUS",
        "BARUERI",
        "CAIERAS",
        "FERRAZ DE VASCONCELLOS",
        "ARUJA",
        "TABOAO DA SERRA",
    ],
    "02": [
        "NOVA GRANADA",
        "ARARAS",
        "PARAGUACU PAULISTA",
        "CAPELA DO ALTO",
        "COTIA",
    ],
    "03": [
        "OSVALDO CRUZ",
    ],
    "04": [
        "SOROCABA",
        "ARACOIABA DA SERRA",
        "VOTORANTIM",
        "SALTO DE PIRAPORA",
        "TAPIRAI",
        "IBIUNA",
        "IBIUNA",
        "ITU",
        "PILAR DO SUL",
        "SALTO",
        "ALUMINIO",
        "PIEDADE",
        "SAO MANUEL",
        "MANDURI",
        "BOTUCATU",
        "ITAPETININGA",
        "ANGATUBA",
        "TATUI",
        "BOITUVA",
        "ARACARIGUAMA",
    ],
    "05": [
        "SAO JOSE DOS CAMPOS",
        "PINDAMONHANGABA",
        "TAUBATE",
        "CARAGUATATUBA",
        "ILHABELA",
        "UBATUBA",
        "SAO SEBASTIAO",
        "LORENA",
        "CACAPAVA",
        "QUELUZ",
        "MAUA",
        "CUNHA",
        "GUARATINGUETA",
        "PARAIBUNA",
        "ITAPEVA",
        "JAMBEIRO",
        "TREMEMBE",
        "RIBEIRÃO PIRES",
        "CAMPOS DO JORDAO",
    ],
    "06": [
        "BAURU",
        "PIRATININGA",
        "PEDERNEIRAS",
        "LENCOIS PAULISTA",
        "PIRAJUI",
        "JAU",
        "AGUDOS",
        "DUARTINA",
        "MACATUBA",
        "IGARACU DO TIETE",
        "BARRA BONITA",
        "BOCAINA",
        "DUARTINA",
        "BARIRI",
        "QUINTANA",
        "OURINHOS",
        "IACANGA",
        "SANTA CRUZ DO RIO PARDO",
        "DOIS CORREGOS",
        "CANITAR",
        "POMPEIA",
        "IPAUSSU",
        "MARILIA",
        "AREALVA",
        "TUPA",
        "SALTO GRANDE",
        "LINS",
        "CARCA",
        "QUATA",
        "GARCA",
        "TIETE",
        "RINOPOLIS",
        "GETULINA",
    ],
    "08": [
        "SANTOS",
        "PRAIA GRANDE",
        "SETE BARRA",
        "SAO VICENTE",
        "GUARUJA",
        "BERTIOGA",
        "ITARIRI",
        "IGUAPE",
        "PERUIBE",
        "CANANEIA",
        "CAJATI",
        "MONGAGUA",
    ],
    "09": [
        "SAO JOSE DO RIO PRETO",
        "JACI",
        "JOSE BONIFACIO",
        "TANABI",
        "NEVES PAULISTA",
        "TABAPUA",
        "CATANDUVA",
        "TANABI",
        "ZACARIAS",
        "MIRASSOLANDIA",
        "SANTA FE DO SUL",
        "JALES",
        "CARDOSO",
        "VOTUPORANGA",
        "PINDORAMA",
        "APARECIDA",
        "CEDRAL",
        "TRES FRONTEIRAS",
    ],
    "10": [
        "CAMPINAS",
        "ITUPEVA",
        "JUNDIAI",
        "CABREUVA",
        "CABREUVA",
        "PAULINIA",
        "ITATIBA",
        "JARINU",
        "LOUVEIRA",
        "VARZEA PAULISTA",
        "VARZEA PAULISTA",
        "CAMPO LIMPO PAULISTA",
        "VALINHOS",
        "AGUAS DE LINODIA",
        "INDAIATUBA",
        "ATIBAIA",
        "HORTOLANDIA",
        "VINHEDO",
        "SERRA NEGRA",
        "JAGUARIUNA",
        "BOM JESUS DOS PERDOES",
        "SOCORRO",
        "PEDREIRA",
    ],
    "12": [
        "ARARAQUARA",
        "FRANCA",
        "SAO SIMAO",
        "RIBEIRAO PRETO",
        "SANTA RITA DO PASSA QUATRO",
        "BARRETOS",
        "PORTO FERREIRA",
        "SAO CARLOS",
        "MONTE AZUL PAULISTA",
        "COLINA",
        "TERRA ROXA",
        "CAJURU",
        "SANTA RITA DO PASSA QUATRO",
        "SANTA ROSA DE VITERBO",
        "SANTO ANTONIO DA ALEGRIA",
        "CRAVINHOS",
        "CLEMENTINA",
        "OLIMPIA",
        "TRABIJU",
        "SERRANA",
        "AMERICO BRASILIENSE",
        "BRODOWSKI",
        "JARDINOPOLIS",
        "LUIS ANTONIO",
        "JABOTICABAL",
        "BARRINHA",
        "BURITIZAL",
        "ITIRAPINA",
        "RIBEIRAO BONITO",
        "TAQUARITININGA",
        "MONTE ALTO",
        "GUAIRA",
        "MATÃO",
        "AVARE",
        "SERTAOZINHO",
    ],
    "13": [
        "ARACATUBA",
        "DESCALVADO",
        "PENAPOLIS",
        "BARBOSA",
        "BIRIGUI",
        "AURIFLAMA",
        "GUARARAPES",
        "BILAC",
        "VALPARAISO",
        "PIACATU",
        "AVANHANDAVA",
        "GUARARAPES",
        "ANDRADINA",
        "CASTILHO",
        "ILHA SOLTEIRA",
        "PEREIRA BARRETO",
        "MIRANDOPOLIS",
        "BURITAMA",
        "AURIFLAMA",
        "BURITAMA",
        "RUBIACEA",
        "AURIFLAMA",
    ],
    "18": [
        "PRESIDENTE PRUDENTE",
        "SANDOVALINA",
        "RANCHARIA",
        "REGENTE FEIJO",
        "NARANDIBA",
        "MARTINOPOLIS",
        "PIRAPOZINHO",
        "ALVARES MACHADO",
        "SANTO ANASTACIO",
        "MARTINOPOLIS",
        "SANTO ANASTACIO",
        "TEODORO SAMPAIO",
        "ADAMANTINA",
        "DRACENA",
        "PARANORAMA",
        "CANDIDO MOTA",
        "TACIBA",
        "ASSIS",
        "PRESIDENTE VENCESLAU",
        "PACAEMBU",
        "PRESIDENTE BERNARDES",
    ],
    "26": [
        "MOMBUCA",
        "PIRACICABA",
        "CAPIVARI",
        "RAFARD",
        "SAO PEDRO",
        "ELIAS FAUSTO",
        "RIO DAS PEDRAS",
        "LIMEIRA",
        "AMERICANA",
        "SANTA BARBARA D OESTE",
        "SUMARE",
        "ESPIRITO SANTO DO PINAL",
        "VARGEM GRANDE DO SUL",
        "LEME",
        "AGUAI",
        "SANTA CRUZ DAS PALMEIRAS",
        "BROTAS",
        "CASA BRANCA",
        "ARTUR NOGUEIRA",
        "SAO JOAO DA BOA VISTA",
        "MOCOCA",
        "COSMOPOLIS",
        "SANTA GERTRUDES",
        "CORDEIROPOLIS",
        "RIO CLARO",
        "ARARAS",
    ],
}
