# Generated by Django 3.1.7 on 2022-12-13 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userallowed',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
