# Generated by Django 4.1.13 on 2025-04-28 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0002_imagemetadata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagemetadata',
            old_name='city_1',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='imagemetadata',
            old_name='city_3',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='imagemetadata',
            old_name='city_2',
            new_name='ocr_code',
        ),
        migrations.RemoveField(
            model_name='imagemetadata',
            name='date_1',
        ),
        migrations.RemoveField(
            model_name='imagemetadata',
            name='date_2',
        ),
        migrations.RemoveField(
            model_name='imagemetadata',
            name='date_3',
        ),
        migrations.RemoveField(
            model_name='imagemetadata',
            name='ocr_code_1',
        ),
        migrations.RemoveField(
            model_name='imagemetadata',
            name='ocr_code_2',
        ),
        migrations.RemoveField(
            model_name='imagemetadata',
            name='ocr_code_3',
        ),
        migrations.AlterField(
            model_name='imagemetadata',
            name='processing_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='image_processing.processingimage'),
        ),
    ]
