# Generated by Django 4.1.13 on 2025-04-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0003_rename_city_1_imagemetadata_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemetadata',
            name='position',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
