# Generated by Django 4.1.13 on 2025-05-10 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0004_imagemetadata_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingimage',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('completed', 'Completo'), ('failed', 'Falhou')], default='pending', max_length=124),
        ),
        migrations.AlterField(
            model_name='processingimage',
            name='processing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_images', to='image_processing.processing'),
        ),
    ]
