# Generated by Django 4.1.13 on 2025-02-24 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("image_processings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessingImageMetadata",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ocr_code_1", models.CharField(blank=True, max_length=256, null=True)),
                ("date_1", models.CharField(blank=True, max_length=256, null=True)),
                ("city_1", models.CharField(blank=True, max_length=256, null=True)),
                ("ocr_code_2", models.CharField(blank=True, max_length=256, null=True)),
                ("date_2", models.CharField(blank=True, max_length=256, null=True)),
                ("city_2", models.CharField(blank=True, max_length=256, null=True)),
                ("ocr_code_3", models.CharField(blank=True, max_length=256, null=True)),
                ("date_3", models.CharField(blank=True, max_length=256, null=True)),
                ("city_3", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "processing_image",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata",
                        to="image_processings.processingimage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
