import pytest

from veredict.image_processing.services.token_processing import (
    map_city_code,
    convert_date_format,
    parse_ocr,
)


@pytest.mark.parametrize(
    "city, expected_codes",
    [
        ("SAO BERNARDO DO CAMPO", ["01"]),
        ("SAO PAULO", ["01"]),
        ("GUARULHOS", ["01"]),
        ("DIADEMA", ["01"]),
        ("SAO CAETANO DO SUL", ["01"]),
        ("MOGI DAS CRUZES", ["01"]),
        ("SANTO ANDRE", ["01"]),
        ("FRANCO DA ROCHA", ["01"]),
        ("FRANCISCO MORATO", ["01"]),
        ("MAIRIPORA", ["01"]),
        ("CARAPICUIBA", ["01"]),
        ("OSASCO", ["01"]),
        ("SUZANO", ["01"]),
        ("EMBU DAS ARTES", ["01"]),
        ("SANTA ISABEL", ["01"]),
        ("SANTANA DE PERNAÍBA", ["01"]),
        ("PIRAPORA DO BOM JESUS", ["01"]),
        ("BARUERI", ["01"]),
        ("CAIERAS", ["01"]),
        ("FERRAZ DE VASCONCELLOS", ["01"]),
        ("ARUJA", ["01"]),
        ("TABOAO DA SERRA", ["01"]),
        ("NOVA GRANADA", ["02"]),
        ("PARAGUACU PAULISTA", ["02"]),
        ("CAPELA DO ALTO", ["02"]),
        ("COTIA", ["02"]),
        ("OSVALDO CRUZ", ["03"]),
        ("SOROCABA", ["04"]),
        ("ARACOIABA DA SERRA", ["04"]),
        ("VOTORANTIM", ["04"]),
        ("SALTO DE PIRAPORA", ["04"]),
        ("TAPIRAI", ["04"]),
        ("IBIUNA", ["04"]),
        ("IBIUNA", ["04"]),
        ("ITU", ["04"]),
        ("PILAR DO SUL", ["04"]),
        ("SALTO", ["04"]),
        ("ALUMINIO", ["04"]),
        ("PIEDADE", ["04"]),
        ("SAO MANUEL", ["04"]),
        ("MANDURI", ["04"]),
        ("BOTUCATU", ["04"]),
        ("ITAPETININGA", ["04"]),
        ("ANGATUBA", ["04"]),
        ("TATUI", ["04"]),
        ("BOITUVA", ["04"]),
        ("ARACARIGUAMA", ["04"]),
        ("SAO JOSE DOS CAMPOS", ["05"]),
        ("PINDAMONHANGABA", ["05"]),
        ("TAUBATE", ["05"]),
        ("CARAGUATATUBA", ["05"]),
        ("ILHABELA", ["05"]),
        ("UBATUBA", ["05"]),
        ("SAO SEBASTIAO", ["05"]),
        ("LORENA", ["05"]),
        ("CACAPAVA", ["05"]),
        ("QUELUZ", ["05"]),
        ("MAUA", ["05"]),
        ("CUNHA", ["05"]),
        ("GUARATINGUETA", ["05"]),
        ("PARAIBUNA", ["05"]),
        ("ITAPEVA", ["05"]),
        ("JAMBEIRO", ["05"]),
        ("TREMEMBE", ["05"]),
        ("RIBEIRÃO PIRES", ["05"]),
        ("CAMPOS DO JORDAO", ["05"]),
        ("BAURU", ["06"]),
        ("PIRATININGA", ["06"]),
        ("PEDERNEIRAS", ["06"]),
        ("LENCOIS PAULISTA", ["06"]),
        ("PIRAJUI", ["06"]),
        ("JAU", ["06"]),
        ("AGUDOS", ["06"]),
        ("DUARTINA", ["06"]),
        ("MACATUBA", ["06"]),
        ("IGARACU DO TIETE", ["06"]),
        ("BARRA BONITA", ["06"]),
        ("BOCAINA", ["06"]),
        ("DUARTINA", ["06"]),
        ("BARIRI", ["06"]),
        ("QUINTANA", ["06"]),
        ("OURINHOS", ["06"]),
        ("IACANGA", ["06"]),
        ("SANTA CRUZ DO RIO PARDO", ["06"]),
        ("DOIS CORREGOS", ["06"]),
        ("CANITAR", ["06"]),
        ("POMPEIA", ["06"]),
        ("IPAUSSU", ["06"]),
        ("MARILIA", ["06"]),
        ("AREALVA", ["06"]),
        ("TUPA", ["06"]),
        ("SALTO GRANDE", ["06"]),
        ("LINS", ["06"]),
        ("CARCA", ["06"]),
        ("QUATA", ["06"]),
        ("GARCA", ["06"]),
        ("TIETE", ["06"]),
        ("RINOPOLIS", ["06"]),
        ("GETULINA", ["06"]),
        ("SANTOS", ["08"]),
        ("PRAIA GRANDE", ["08"]),
        ("SETE BARRA", ["08"]),
        ("SAO VICENTE", ["08"]),
        ("GUARUJA", ["08"]),
        ("BERTIOGA", ["08"]),
        ("ITARIRI", ["08"]),
        ("IGUAPE", ["08"]),
        ("PERUIBE", ["08"]),
        ("CANANEIA", ["08"]),
        ("CAJATI", ["08"]),
        ("MONGAGUA", ["08"]),
        ("SAO JOSE DO RIO PRETO", ["09"]),
        ("JACI", ["09"]),
        ("JOSE BONIFACIO", ["09"]),
        ("TANABI", ["09"]),
        ("NEVES PAULISTA", ["09"]),
        ("TABAPUA", ["09"]),
        ("CATANDUVA", ["09"]),
        ("TANABI", ["09"]),
        ("ZACARIAS", ["09"]),
        ("MIRASSOLANDIA", ["09"]),
        ("SANTA FE DO SUL", ["09"]),
        ("JALES", ["09"]),
        ("CARDOSO", ["09"]),
        ("VOTUPORANGA", ["09"]),
        ("PINDORAMA", ["09"]),
        ("APARECIDA", ["09"]),
        ("CEDRAL", ["09"]),
        ("TRES FRONTEIRAS", ["09"]),
        ("CAMPINAS", ["10"]),
        ("ITUPEVA", ["10"]),
        ("JUNDIAI", ["10"]),
        ("CABREUVA", ["10"]),
        ("CABREUVA", ["10"]),
        ("PAULINIA", ["10"]),
        ("ITATIBA", ["10"]),
        ("JARINU", ["10"]),
        ("LOUVEIRA", ["10"]),
        ("VARZEA PAULISTA", ["10"]),
        ("VARZEA PAULISTA", ["10"]),
        ("CAMPO LIMPO PAULISTA", ["10"]),
        ("VALINHOS", ["10"]),
        ("AGUAS DE LINODIA", ["10"]),
        ("INDAIATUBA", ["10"]),
        ("ATIBAIA", ["10"]),
        ("HORTOLANDIA", ["10"]),
        ("VINHEDO", ["10"]),
        ("SERRA NEGRA", ["10"]),
        ("JAGUARIUNA", ["10"]),
        ("BOM JESUS DOS PERDOES", ["10"]),
        ("SOCORRO", ["10"]),
        ("PEDREIRA", ["10"]),
        ("ARARAQUARA", ["12"]),
        ("FRANCA", ["12"]),
        ("SAO SIMAO", ["12"]),
        ("RIBEIRAO PRETO", ["12"]),
        ("SANTA RITA DO PASSA QUATRO", ["12"]),
        ("BARRETOS", ["12"]),
        ("PORTO FERREIRA", ["12"]),
        ("SAO CARLOS", ["12"]),
        ("MONTE AZUL PAULISTA", ["12"]),
        ("COLINA", ["12"]),
        ("TERRA ROXA", ["12"]),
        ("CAJURU", ["12"]),
        ("SANTA RITA DO PASSA QUATRO", ["12"]),
        ("SANTA ROSA DE VITERBO", ["12"]),
        ("SANTO ANTONIO DA ALEGRIA", ["12"]),
        ("CRAVINHOS", ["12"]),
        ("CLEMENTINA", ["12"]),
        ("OLIMPIA", ["12"]),
        ("TRABIJU", ["12"]),
        ("SERRANA", ["12"]),
        ("AMERICO BRASILIENSE", ["12"]),
        ("BRODOWSKI", ["12"]),
        ("JARDINOPOLIS", ["12"]),
        ("LUIS ANTONIO", ["12"]),
        ("JABOTICABAL", ["12"]),
        ("BARRINHA", ["12"]),
        ("BURITIZAL", ["12"]),
        ("ITIRAPINA", ["12"]),
        ("RIBEIRAO BONITO", ["12"]),
        ("TAQUARITININGA", ["12"]),
        ("MONTE ALTO", ["12"]),
        ("GUAIRA", ["12"]),
        ("MATÃO", ["12"]),
        ("ARACATUBA", ["13"]),
        ("DESCALVADO", ["13"]),
        ("PENAPOLIS", ["13"]),
        ("BARBOSA", ["13"]),
        ("BIRIGUI", ["13"]),
        ("AURIFLAMA", ["13"]),
        ("GUARARAPES", ["13"]),
        ("BILAC", ["13"]),
        ("VALPARAISO", ["13"]),
        ("PIACATU", ["13"]),
        ("AVANHANDAVA", ["13"]),
        ("GUARARAPES", ["13"]),
        ("ANDRADINA", ["13"]),
        ("CASTILHO", ["13"]),
        ("ILHA SOLTEIRA", ["13"]),
        ("PEREIRA BARRETO", ["13"]),
        ("MIRANDOPOLIS", ["13"]),
        ("BURITAMA", ["13"]),
        ("AURIFLAMA", ["13"]),
        ("BURITAMA", ["13"]),
        ("RUBIACEA", ["13"]),
        ("AURIFLAMA", ["13"]),
        ("PRESIDENTE PRUDENTE", ["18"]),
        ("SANDOVALINA", ["18"]),
        ("RANCHARIA", ["18"]),
        ("REGENTE FEIJO", ["18"]),
        ("NARANDIBA", ["18"]),
        ("MARTINOPOLIS", ["18"]),
        ("PIRAPOZINHO", ["18"]),
        ("ALVARES MACHADO", ["18"]),
        ("SANTO ANASTACIO", ["18"]),
        ("MARTINOPOLIS", ["18"]),
        ("SANTO ANASTACIO", ["18"]),
        ("TEODORO SAMPAIO", ["18"]),
        ("ADAMANTINA", ["18"]),
        ("DRACENA", ["18"]),
        ("PARANORAMA", ["18"]),
        ("CANDIDO MOTA", ["18"]),
        ("TACIBA", ["18"]),
        ("ASSIS", ["18"]),
        ("PRESIDENTE VENCESLAU", ["18"]),
        ("PACAEMBU", ["18"]),
        ("PRESIDENTE BERNARDES", ["18"]),
        ("MOMBUCA", ["26"]),
        ("PIRACICABA", ["26"]),
        ("CAPIVARI", ["26"]),
        ("RAFARD", ["26"]),
        ("SAO PEDRO", ["26"]),
        ("ELIAS FAUSTO", ["26"]),
        ("RIO DAS PEDRAS", ["26"]),
        ("LIMEIRA", ["26"]),
        ("AMERICANA", ["26"]),
        ("SANTA BARBARA D OESTE", ["26"]),
        ("SUMARE", ["26"]),
        ("ESPIRITO SANTO DO PINAL", ["26"]),
        ("VARGEM GRANDE DO SUL", ["26"]),
        ("LEME", ["26"]),
        ("AGUAI", ["26"]),
        ("SANTA CRUZ DAS PALMEIRAS", ["26"]),
        ("BROTAS", ["26"]),
        ("CASA BRANCA", ["26"]),
        ("ARTUR NOGUEIRA", ["26"]),
        ("SAO JOAO DA BOA VISTA", ["26"]),
        ("MOCOCA", ["26"]),
        ("COSMOPOLIS", ["26"]),
        ("SANTA GERTRUDES", ["26"]),
        ("CORDEIROPOLIS", ["26"]),
        ("RIO CLARO", ["26"]),
        ("ARARAS", ["02", "26"]),
    ],
)
def test_city_code(city, expected_codes):
    assert map_city_code(city) == expected_codes


def test_date_format():
    input_date = "01/02/2025"
    assert convert_date_format(input_date) == "20250201"


@pytest.mark.parametrize(
    "ocr,expected",
    [
        ("1", "00001"),
        ("12", "00012"),
        ("123", "00123"),
        ("1234", "01234"),
        ("12345", "12345"),
    ],
)
def test_parse_ocr(ocr, expected):
    assert parse_ocr(ocr) == expected
