# Generated by Django 3.1.7 on 2021-03-15 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0003_auto_20210315_0549'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='documentos/')),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='attachments', to='attendances.attendance')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
