# Generated by Django 3.1.7 on 2021-03-28 05:45

from django.db import migrations, models
import lavocat.attendances.validators


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0008_auto_20210327_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='document_id',
            field=models.CharField(max_length=11, validators=[lavocat.attendances.validators.validate_document_id]),
        ),
    ]
