# Generated by Django 3.1.7 on 2021-04-07 04:25

from django.db import migrations, models
import lavocat.attendances.models
import storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0009_auto_20210328_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Documentação pendente'), (2, 'Em andamento'), (3, 'À contatar'), (4, 'Concluído')]),
        ),
        migrations.AlterField(
            model_name='attendancefile',
            name='file',
            field=models.FileField(storage=storage_backends.MediaStorage(), upload_to=lavocat.attendances.models.upload_to),
        ),
    ]
