# Generated by Django 3.1.7 on 2021-04-23 05:59

from django.db import migrations, models
import lavocat.attendances.validators


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0010_auto_20210407_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='document_id',
            field=models.CharField(max_length=11, null=True, validators=[lavocat.attendances.validators.validate_document_id]),
        ),
    ]
