# Generated by Django 3.1.7 on 2021-04-27 15:50

from django.db import migrations, models
import lavocat.attendances.validators


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0011_auto_20210423_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='document_id',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[lavocat.attendances.validators.validate_document_id]),
        ),
    ]
