# Generated by Django 3.1.7 on 2021-05-28 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0012_auto_20210427_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancefile',
            name='attendance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='attendances.attendance'),
        ),
    ]
