# Generated by Django 3.1.7 on 2021-10-28 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0013_auto_20210528_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='status_resume',
            field=models.TextField(null=True),
        ),
    ]
