# Generated by Django 3.1.7 on 2023-09-04 01:33

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ('attendances', '0016_attendancefile_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='services_provided',
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ('DPVAT', 'DPVAT'),
                    ('AUXILIO_DOENCA', 'Auxílio Doença'),
                    ('AUXILIO_ACIDENTE', 'Auxílio Acidente'),
                    ('LOAS', 'LOAS'),
                    ('APOSENTADORIA', 'Aposentadoria'),
                    ('ACAO_CONTRA_CONDUTOR', 'Ação Contra Condutor'),
                    ('ACAO_TRABALHISTA', 'Ação Trabalhista'),
                    ('ACAO_PREVIDENCIARIA', 'Ação Previdenciária'),
                    ('SEGURO_DE_VIDA_PROPRIO', 'Seguro de Vida Próprio'),
                    ('SEGURO_CONDUTOR', 'Seguro Condutor'),
                    ('SEGURO_DE_VIDA_EMPRESARIAL', 'Seguro de Vida Empresarial'),
                    ('SEGURO_DE_VIDA_NO_BANCO', 'Seguro de Vida no Banco'),
                ],
                max_length=124,
                null=True,
            ),
        ),
    ]
