# Generated by Django 3.1.7 on 2023-12-09 20:11

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0020_auto_20230905_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='resume',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='services_types',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('DPVAT', 'DPVAT'), ('AUXILIO_DOENCA', 'Auxílio Doença'), ('AUXILIO_ACIDENTE', 'Auxílio Acidente'), ('LOAS', 'LOAS'), ('APOSENTADORIA', 'Aposentadoria'), ('ACAO_INDENIZATORIA', 'Ação Indenizatória'), ('ACAO_TRABALHISTA', 'Ação Trabalhista'), ('ACAO_PREVIDENCIARIA', 'Ação Previdenciária'), ('SEGURO_DE_VIDA_PROPRIO', 'Seguro de Vida Próprio'), ('SEGURO_CONDUTOR', 'Seguro Condutor'), ('SEGURO_DE_VIDA_EMPRESARIAL', 'Seguro de Vida Empresarial'), ('SEGURO_DE_VIDA_NO_BANCO', 'Seguro de Vida no Banco'), ('PENSAO_POR_MORTE', 'Pensão por Morte')], max_length=124, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Documentação pendente'), (2, 'Em andamento'), (3, 'À contatar'), (4, 'Concluído')], null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status_resume',
            field=models.TextField(blank=True, null=True),
        ),
    ]
