# Generated by Django 3.1.7 on 2024-01-07 01:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('attendances', '0021_auto_20231209_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='source',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
