name: Run Backend Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: veredict
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres -d veredict"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Create `.env.test` file
        run: |
          > backend/.env.test
          echo "DEBUG=True" >> backend/.env.test
          echo "SECRET_KEY=secret" >> backend/.env.test
          echo "ALLOWED_HOSTS=*" >> backend/.env.test

      - name: Set up Docker Compose for Tests
        run: |
          docker-compose -f compose.backend.tests.yml up -d --build
          docker-compose -f compose.backend.tests.yml run --rm backend pytest --disable-warnings

      - name: Debug Running Containers
        run: docker ps -a

      - name: Stop Docker Containers After Tests
        run: docker-compose -f compose.backend.tests.yml down