name: Run Backend Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: veredict
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres -d veredict"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Create `.env.test` file
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_STORAGE_BUCKET_NAME: ${{ secrets.AWS_STORAGE_BUCKET_NAME }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          CELERY_BROKER_URL: ${{ secrets.CELERY_BROKER_URL }}
        run: |
          > backend/.env.test
          echo "DEBUG=True" >> backend/.env.test
          echo "SECRET_KEY=secret" >> backend/.env.test
          echo "ALLOWED_HOSTS=*" >> backend/.env.test
          echo "CELERY_BROKER_URL=CELERY_BROKER_URL" >> backend/.env.test
          echo "USE_S3=True" >> backend/.env.test
          echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> backend/.env.test
          echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> backend/.env.test
          echo "AWS_STORAGE_BUCKET_NAME=$AWS_STORAGE_BUCKET_NAME" >> backend/.env.test
          echo "AWS_REGION=$AWS_REGION" >> backend/.env.test

      - name: Set up Docker Compose for Tests
        run: |
          docker-compose -f compose.backend.tests.yml up -d --build
          docker-compose -f compose.backend.tests.yml run --rm backend pytest --disable-warnings

      - name: Debug Running Containers
        run: docker ps -a

      - name: Stop Docker Containers After Tests
        run: docker-compose -f compose.backend.tests.yml down