name: Deploy to AWS Lightsail

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Decode SSH Private Key
        id: decode-key
        run: |
          echo "${{ secrets.LIGHTSAIL_SSH_KEY }}" | base64 --decode > decoded_key
          echo "DECODED_KEY<<EOF" >> $GITHUB_ENV
          cat decoded_key >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ env.DECODED_KEY }}

      - name: Deploy to Lightsail
        env:
          ALLOWED_HOSTS: ${{ secrets.BACKEND_ALLOWED_HOSTS }}
          SECRET_KEY: ${{ secrets.BACKEND_SECRET_KEY }}
          DATABASE_URL: ${{ secrets.BACKEND_DATABASE_URL }}
          FRONTEND_API_URL: ${{ secrets.FRONTEND_API_URL }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_STORAGE_BUCKET_NAME: ${{ secrets.AWS_STORAGE_BUCKET_NAME }}
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.LIGHTSAIL_IP }} << EOF
            cd /home/ubuntu/veredict
          
            # Force reset and pull latest code
            git fetch --all
            git reset --hard origin/main
            git clean -fd
            git pull origin main --force
            
            # Set environment variables inside the SSH session
            export SECRET_KEY="${SECRET_KEY}"
            export ALLOWED_HOSTS="${ALLOWED_HOSTS}"
            export DATABASE_URL="${DATABASE_URL}"
            export FRONTEND_API_URL="${FRONTEND_API_URL}"
            export AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID}"
            export AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY}"
            export AWS_STORAGE_BUCKET_NAME="${AWS_STORAGE_BUCKET_NAME}"
            export NEXT_PUBLIC_API_URL="${NEXT_PUBLIC_API_URL}"
          
            # Create an empty file (truncate if exists)
            > backend/.env.prod
            
            # Append environment variables
            echo "DEBUG=False" >> backend/.env.prod
            echo "SECRET_KEY=$SECRET_KEY" >> backend/.env.prod
            echo "ALLOWED_HOSTS=$ALLOWED_HOSTS" >> backend/.env.prod
            echo "DATABASE_URL=$DATABASE_URL" >> backend/.env.prod
            echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> backend/.env.prod
            echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> backend/.env.prod
            echo "AWS_STORAGE_BUCKET_NAME=$AWS_STORAGE_BUCKET_NAME" >> backend/.env.prod
          
            # Create an empty file (truncate if exists)
            > frontend/.env.production
            
            # Append environment variables
            echo "NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL" >> frontend/.env.production
            
            # Build and deploy with Docker Compose
            docker-compose -f compose.prod.yml down --volumes --remove-orphans
            docker system prune -af
            docker-compose -f compose.prod.yml up -d --build
            
            # Collectic staticfiles
            docker-compose -f compose.prod.yml run backend python manage.py collectstatic --noinput
            
            # Run database migrations
            docker-compose -f compose.prod.yml run backend python manage.py migrate
          EOF